version: '3.3'

services:

  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/videos:/opt/selenoid/video"
      - /dev/shm:/dev/shm
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/videos
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-limit", "2", "-mem", "1g", "-cpu", "1.5"]
    ports:
      - "4444:4444"
  
  selenoid-ui:
    image: aerokube/selenoid-ui
    depends_on:
      - selenoid
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "9090:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  
  jenkins:
    image : jenkins
    ports:
      - "8080:8080"
  
  mongo:
    image: mongo:3.3
    ports:
      - "27017:27017"
  
  logger:
    image: automation/logger
    ports:
     - "4000:4000"