version: "3.3"

services:

  mongo:
    image: mongo:3.3
    ports:
     - "27017:27017"

  hub:
    image: selenium/hub
    ports:
     - "4444:4444"
    environment:
     - GRID_TIMEOUT=300
     - GRID_BROWSER_TIMEOUT=300

  chrome:
    image: selenium/node-chrome-debug
    ports:
     - "5900"
    depends_on:
     - hub
    environment:
     - HUB_PORT_4444_TCP_ADDR=hub
     - HUB_PORT_4444_TCP_PORT=4444
    volumes:
    - /dev/shm:/dev/shm
  
