version: "2.2"

services:

  mongo:
    image: mongo:3.3
    ports:
     - "32001:27017"

  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/videos:/opt/selenoid/video"
      - /dev/shm:/dev/shm
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/videos
      - DOCKER_API_VERSION=1.35
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-limit", "35", "-mem", "3g", "-cpu", "2", "timeout", "3m0s"]
    ports:
      - "32005:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui
    depends_on:
      - selenoid
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "32004:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  logger:
    image: minutemedia/logger:5.5
    ports:
     - "4000:4000"
    links:
     - mongo

  proxy:
    image: qautomatron/docker-browsermob-proxy
    ports:
      - "32006:9090"
      - "32007-32600:32007-32600"
    environment:
      - PORT_RANGE=32007-32600

  mail:
   image: minutemedia/mail:2.0
   ports:
    - "32002:3000"

  mongoui:
   image : minutemedia/mongoexpress:1.3
   links:
    - mongo
   ports:
    - "32003:8081"
   environment:
    - ME_CONFIG_BASICAUTH_USERNAME=*****
    - ME_CONFIG_BASICAUTH_PASSWORD=*****
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_ADMINUSERNAME=*****
    - ME_CONFIG_MONGODB_ADMINPASSWORD=*****

  jenkins:
   image: minutemedia/jenkins-auto:1.0
   ports:
    - "8080:8080"
   links:
    - mongo
    - selenoid
   volumes:
    - ./videos:/videos
